// Run with: node scripts/generate-icons.js
// Generates simple PWA icons using Canvas (Node.js with canvas package)
// If canvas is not available, icons are created via the game itself on first load

import { createCanvas } from 'canvas';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

function drawIcon(size) {
  const canvas = createCanvas(size, size);
  const ctx = canvas.getContext('2d');

  // Background gradient
  const grad = ctx.createRadialGradient(size/2, size/2, 0, size/2, size/2, size/2);
  grad.addColorStop(0, '#3a1a7e');
  grad.addColorStop(1, '#1a0a3e');
  ctx.fillStyle = grad;
  ctx.beginPath();
  ctx.roundRect(0, 0, size, size, size * 0.2);
  ctx.fill();

  // Stars
  ctx.fillStyle = 'rgba(255,255,255,0.6)';
  const stars = [[0.15,0.2],[0.8,0.15],[0.9,0.7],[0.1,0.8],[0.5,0.1]];
  stars.forEach(([x,y]) => {
    ctx.beginPath();
    ctx.arc(x*size, y*size, size*0.02, 0, Math.PI*2);
    ctx.fill();
  });

  // Character body (alien baby mermaid)
  const cx = size * 0.5;
  const cy = size * 0.45;
  const scale = size / 192;

  // Mermaid tail
  ctx.fillStyle = '#00e5ff';
  ctx.beginPath();
  ctx.ellipse(cx, cy + 35*scale, 18*scale, 28*scale, 0, 0, Math.PI*2);
  ctx.fill();

  // Tail fin
  ctx.fillStyle = '#00b8d4';
  ctx.beginPath();
  ctx.moveTo(cx - 20*scale, cy + 55*scale);
  ctx.lineTo(cx, cy + 70*scale);
  ctx.lineTo(cx + 20*scale, cy + 55*scale);
  ctx.closePath();
  ctx.fill();

  // Dress
  ctx.fillStyle = '#4caf50';
  ctx.beginPath();
  ctx.ellipse(cx, cy + 10*scale, 22*scale, 20*scale, 0, 0, Math.PI*2);
  ctx.fill();

  // Body
  ctx.fillStyle = '#66bb6a';
  ctx.beginPath();
  ctx.ellipse(cx, cy - 10*scale, 18*scale, 22*scale, 0, 0, Math.PI*2);
  ctx.fill();

  // Head
  ctx.fillStyle = '#81c784';
  ctx.beginPath();
  ctx.ellipse(cx, cy - 38*scale, 20*scale, 22*scale, 0, 0, Math.PI*2);
  ctx.fill();

  // Eyes
  ctx.fillStyle = 'white';
  ctx.beginPath();
  ctx.ellipse(cx - 8*scale, cy - 40*scale, 7*scale, 8*scale, 0, 0, Math.PI*2);
  ctx.ellipse(cx + 8*scale, cy - 40*scale, 7*scale, 8*scale, 0, 0, Math.PI*2);
  ctx.fill();

  ctx.fillStyle = '#1a1a2e';
  ctx.beginPath();
  ctx.arc(cx - 7*scale, cy - 40*scale, 5*scale, 0, Math.PI*2);
  ctx.arc(cx + 9*scale, cy - 40*scale, 5*scale, 0, Math.PI*2);
  ctx.fill();

  ctx.fillStyle = 'white';
  ctx.beginPath();
  ctx.arc(cx - 5*scale, cy - 42*scale, 2*scale, 0, Math.PI*2);
  ctx.arc(cx + 11*scale, cy - 42*scale, 2*scale, 0, Math.PI*2);
  ctx.fill();

  // Wig (red)
  ctx.fillStyle = '#e53935';
  ctx.beginPath();
  ctx.ellipse(cx, cy - 52*scale, 22*scale, 16*scale, 0, 0, Math.PI);
  ctx.fill();
  // Hair strands
  for (let i = -2; i <= 2; i++) {
    ctx.beginPath();
    ctx.moveTo(cx + i * 8*scale, cy - 58*scale);
    ctx.quadraticCurveTo(cx + i * 10*scale, cy - 75*scale, cx + i * 8*scale + 5*scale, cy - 85*scale);
    ctx.lineWidth = 3*scale;
    ctx.strokeStyle = '#c62828';
    ctx.stroke();
  }

  // Antennae
  ctx.strokeStyle = '#81c784';
  ctx.lineWidth = 2*scale;
  ctx.beginPath();
  ctx.moveTo(cx - 10*scale, cy - 58*scale);
  ctx.lineTo(cx - 15*scale, cy - 72*scale);
  ctx.stroke();
  ctx.beginPath();
  ctx.moveTo(cx + 10*scale, cy - 58*scale);
  ctx.lineTo(cx + 15*scale, cy - 72*scale);
  ctx.stroke();

  // Antenna tips
  ctx.fillStyle = '#ff80ab';
  ctx.beginPath();
  ctx.arc(cx - 15*scale, cy - 72*scale, 3*scale, 0, Math.PI*2);
  ctx.arc(cx + 15*scale, cy - 72*scale, 3*scale, 0, Math.PI*2);
  ctx.fill();

  // Ice sparkle
  ctx.fillStyle = '#80d8ff';
  ctx.font = `${20*scale}px serif`;
  ctx.fillText('❄', cx + 25*scale, cy + 5*scale);

  return canvas.toBuffer('image/png');
}

try {
  mkdirSync(join(__dirname, '../public/icons'), { recursive: true });
  writeFileSync(join(__dirname, '../public/icons/icon-192.png'), drawIcon(192));
  writeFileSync(join(__dirname, '../public/icons/icon-512.png'), drawIcon(512));
  console.log('Icons generated successfully!');
} catch (e) {
  console.log('Canvas not available, icons will be generated by the app:', e.message);
}
